$ErrorActionPreference = "Stop"

$spName = "databricks-jobs-service-principal"
$spAppId = "d519efa6-3cb5-4fa0-8535-c657175be154"
$account = az account show | ConvertFrom-Json

# SAVE TO CURRENT DIRECTORY
$currentDir = Get-Location
$reportFile = Join-Path $currentDir "Databricks-Report-$(Get-Date -Format 'yyyyMMdd-HHmmss').html"

Write-Host ""
Write-Host "CREATING REPORT IN: $currentDir" -ForegroundColor Cyan
Write-Host ""

$html = @"
<html>
<head>
<title>Databricks Setup Report</title>
<style>
body{font-family:Arial;margin:40px;background:white;color:black}
.container{max-width:1000px;margin:0 auto;background:white;padding:30px}
h1{color:black;border-bottom:2px solid black;padding-bottom:10px}
h2{color:black;margin-top:25px;border-bottom:1px solid gray;padding-bottom:8px}
h3{color:black;margin-top:15px}
table{width:100%;border-collapse:collapse;margin:15px 0}
th,td{border:1px solid black;padding:10px;text-align:left}
th{background:lightgray;color:black}
tr:nth-child(even){background:whitesmoke}
.box{background:whitesmoke;border:1px solid gray;padding:15px;margin:15px 0}
ul{line-height:1.6}
</style>
</head>
<body>
<div class="container">

<h1>Databricks Service Principal Setup Report</h1>

<div class="box">
<p><strong>Setup Date:</strong> $(Get-Date -Format 'MMMM dd, yyyy hh:mm:ss tt')</p>
<p><strong>Configured By:</strong> $($account.user.name)</p>
<p><strong>Subscription:</strong> $($account.name)</p>
<p><strong>Status:</strong> COMPLETE</p>
</div>

<h2>Service Principal Details</h2>
<table>
<tr><th>Property</th><th>Value</th></tr>
<tr><td>Display Name</td><td>$spName</td></tr>
<tr><td>Application ID</td><td>$spAppId</td></tr>
<tr><td>Status</td><td>ACTIVE</td></tr>
<tr><td>Date</td><td>$(Get-Date -Format 'MMMM dd, yyyy')</td></tr>
</table>

<h2>Databricks Workspaces Configured</h2>

<div class="box">
<h3>Workspace 1: pyx-warehouse-prod PREPROD</h3>
<p><strong>URL:</strong> https://adb-2756318924173706.6.azuredatabricks.net</p>
<p><strong>Resource Group:</strong> rg-warehouse-preprod</p>
<p><strong>Configuration:</strong></p>
<ul>
<li>Service principal added to admins group</li>
<li>Service principal added to prod-datateam group</li>
<li>5 users configured</li>
</ul>
</div>

<div class="box">
<h3>Workspace 2: pyxlake-databricks PROD</h3>
<p><strong>URL:</strong> https://adb-3248848193480666.6.azuredatabricks.net</p>
<p><strong>Resource Group:</strong> rg-adls-poc</p>
<p><strong>Configuration:</strong></p>
<ul>
<li>Service principal added to admins group</li>
<li>Service principal added to datateam group</li>
<li>5 users configured</li>
</ul>
</div>

<h2>User Access Configuration</h2>

<table>
<tr>
<th>User Email</th>
<th>Permission Level</th>
<th>Workspace Access</th>
<th>Cluster Creation</th>
<th>Groups</th>
</tr>
<tr>
<td>preyash.patel@pyxhealth.com</td>
<td>MANAGER</td>
<td>YES</td>
<td>YES</td>
<td>admins, prod-datateam</td>
</tr>
<tr>
<td>sheela@pyxhealth.com</td>
<td>READ ONLY</td>
<td>YES</td>
<td>NO</td>
<td>None</td>
</tr>
<tr>
<td>brian.burge@pyxhealth.com</td>
<td>READ ONLY</td>
<td>YES</td>
<td>NO</td>
<td>None</td>
</tr>
<tr>
<td>robert@pyxhealth.com</td>
<td>READ ONLY</td>
<td>YES</td>
<td>NO</td>
<td>None</td>
</tr>
<tr>
<td>hunter@pyxhealth.com</td>
<td>READ ONLY</td>
<td>YES</td>
<td>NO</td>
<td>None</td>
</tr>
</table>

<h2>Setup Summary</h2>

<table>
<tr><th>Item</th><th>Count</th></tr>
<tr><td>Workspaces Configured</td><td>2</td></tr>
<tr><td>Service Principals Created</td><td>1</td></tr>
<tr><td>Users Configured</td><td>5</td></tr>
<tr><td>Groups Configured</td><td>4</td></tr>
<tr><td>Setup Method</td><td>Automated Script + Manual UI</td></tr>
</table>

<h2>Next Steps</h2>
<ol>
<li>Update Databricks jobs to use service principal: $spName</li>
<li>Test service principal permissions</li>
<li>Verify users can access workspaces</li>
<li>Contact account admin (John or Tony) to grant Preyash user management</li>
<li>Set up monitoring</li>
</ol>

<div class="box">
<p><strong>Report Generated By:</strong> Syed Rizvi</p>
<p><strong>Date:</strong> $(Get-Date -Format 'MMMM dd, yyyy hh:mm:ss tt')</p>
<p>Databricks Service Principal Setup Complete</p>
</div>

</div>
</body>
</html>
"@

[System.IO.File]::WriteAllText($reportFile, $html, [System.Text.Encoding]::ASCII)

Write-Host ""
Write-Host "=============================================" -ForegroundColor Green
Write-Host "REPORT SAVED!" -ForegroundColor Green
Write-Host "=============================================" -ForegroundColor Green
Write-Host ""
Write-Host "FILE LOCATION:" -ForegroundColor Yellow
Write-Host $reportFile -ForegroundColor Cyan
Write-Host ""
Write-Host "Opening report..." -ForegroundColor Yellow
Write-Host ""

Start-Process $reportFile

Write-Host "DONE" -ForegroundColor Green
